### PR TITLE
Fixed Telegram on Python 3.10 by bumping python-telegram-bot version

### LINKED ISSUE #74: [TelegramBot] not working on latest Python 3.10.2
Fresh install of `torrt` (v1.0.0):
`pip install --user torrt[telegram]`

`torrt run_bots` prints the following to log:
```
python3.10/site-packages/telegram/utils/request.py:40: UserWarning: python-telegram-bot wasn't properly installed. Please refer to README.rst on how to properly install.
warnings.warn("python-telegram-bot wasn't properly installed. Please refer to README.rst on "
ERROR: TelegramBot: You have not installed python-telegram-bot library.
```

Initial investigation showed, that `torrt` have it's dependency on telegram-bot-library hardwired as:
```python-telegram-bot >=11.1.0, <12.0.0a0``` with currently resolves to `python-telegram-bot==11.1.0`

inside the mentioned library is the following:
```
...
try:
    import telegram.vendor.ptb_urllib3.urllib3 as urllib3
    import telegram.vendor.ptb_urllib3.urllib3.contrib.appengine as appengine
    from telegram.vendor.ptb_urllib3.urllib3.connection import HTTPConnection
    from telegram.vendor.ptb_urllib3.urllib3.fields import RequestField
    from telegram.vendor.ptb_urllib3.urllib3.util.timeout import Timeout
except ImportError:
  try:
  ...
  except ImportError:
          warnings.warn(
              "python-telegram-bot wasn't properly installed. Please refer to README.rst on "
              "how to properly install."
          )
...
```

Trying even the first import by hand (`import telegram.vendor.ptb_urllib3.urllib3 as urllib3`) causes this:
```
  File "python3.10/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/selectors.py", line 11, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

So, it seems like it's the perfect time to update `torrt`'s dependency.

PS: I'll look into this. Just creating this issue to keep track of it.

### PR DESCRIPTION
**Pull request by NecroKote**
Self-explanatory

Fixes #74.

⚠️ additional testing advised

Also, I also used `black` to format Bot's source - I think we should use it all over the codebase to reduce the burden of keeping code style intact.

### CODE REVIEW

**Comment by idlesign** [comment]
Thank you.
Please do not apply black formatting just yet. 
We'd rather need to open a discussion and if agreed apply it throughout the whole code base in one do.

**Comment by NecroKote** [comment]
I don't think that reverting `black` for this case have any sense at this point as most of the bot's file was affected anyway. 

But I agree that introducing `black` should be centralized.

**Comment by idlesign** [comment]
> [...] as most of the bot's file was affected anyway.

But it has not. You may compare lines count changed in either case to see the difference.

**Comment by NecroKote** [comment]
@idlesign, I've removed all black-induced things. Pls review and consider merging.
Then I may rebase take a look at #77 again

**Comment by idlesign** [comment]
Seems fine, but without tests can't say for sure %)
Let's try to merge. But mocked tests would be nice.

**Comment by idlesign** [comment]
Thank you.

**Pull request merged**
